#!/usr/bin/env php
<?php
function shutdown() {
    passthru('systemctl --user start radiotext.service');
    passthru("/home/broadcast/switch_input background");
}

function update_meta($song) {
    passthru('/home/broadcast/radiotext '.escapeshellarg($song));
}

$msg = new http\Message(STDIN, FALSE);
$url = new http\Url($msg->getRequestUrl());
$qs = new http\QueryString($url->query);

$is_update = $qs->getString('mode') === 'updinfo';
$is_stream = $msg->getRequestMethod() === 'PUT' || $msg->getRequestMethod() === 'SOURCE';

if ($is_update) {
    // Collect artist name
    $np = "{$qs->getString('artist')} - {$qs->getString('title')}";
    update_meta($np);
    // Answer OK
    print("HTTP/1.0 200 OK\r\n\r\n");
} elseif ($is_stream) {
    // Collect stream name
    $name = $msg->getHeader("Ice-Name");
    passthru('systemctl --user stop radiotext.service');
    update_meta($name);
    // Answer OK
    print("HTTP/1.0 200 OK\r\n\r\n");
    // Listen to input and route using JACK
    register_shutdown_function('shutdown');
    passthru("/home/broadcast/switch_input --sleep vlc >/dev/null &");
    passthru("exec cvlc -A jack - --no-jack-auto-connect --play-and-exit");
} else {
    print(
        "HTTP/1.0 400 Bad Request\r\n\r\n<!doctype html>\n<html lang=en>".
        "<head><meta charset=utf-8><title>Zoupcast</title></head>".
        "<h1>Zoupcast</h1><p>This means you have Zoupcast up and running. ".
        "Use the following parameters on Icecast client:</p><ul>".
        "<li>Vorbis codec".
        "<li>Use UTF-8 for metadata".
        "<li>Rather high quality (>=160kbps)".
        "<li>Any username and password".
        "<li>Any mount point".
        "</ul>"
    );
}
